spring.application.name=order-service
server.port=${PORT:8082}

# ----- PostgreSQL -----
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ----- JSON -----
spring.jackson.time-zone=UTC

# ----- JWT (signs tokens WITH role claim) -----
app.jwt.secret=${JWT_SECRET:change_this_to_a_long_random_secret_string_at_least_32_chars}
app.jwt.expiration-ms=604800000

# ----- Admin registration secret -----
app.admin.secret=${ADMIN_SECRET:OmsAdmin2026Secret}

# ----- Eureka -----
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# ----- Actuator -----
management.endpoints.web.exposure.include=health,info

# ----- Kafka (producer of order-events) -----
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
